name: c2cp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^7.0.0
  flutter_bloc: ^7.3.3
  shared_preferences: ^2.2.2
  bloc_concurrency: ^0.1.0
  dio: ^5.4.0
  get_it: ^7.6.7
  clay_containers: ^0.3.4
  go_router: ^13.2.0
  socket_io_client: ^2.0.3+1
  analyzer: ^6.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_with_people.png
    - assets/gamemode-background.jpg
  